### ISSUE TITLE
"Wrong" url when clicking copy button

### ISSUE THREAD

**Issue by jostein-skaar** [Shtian/AuthentiClash#68]
When I click the copy button, I get the old vercel-url. 
![image](https://github.com/Shtian/AuthentiClash/assets/429242/aedd2f14-4ff7-4e92-ac82-39ce294fb9ac)

Also on the about-page:
![image](https://github.com/Shtian/AuthentiClash/assets/429242/59a56074-2219-47fd-8778-c26103743aee)

**Comment by Shtian** [comment]
Added a redirect for authenticlash.vercel.app to www.authenticlash.app and updated the about URL :)
